In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn  as sns
%matplotlib inline

from sklearn import datasets

In [3]:
df_cutting=pd.read_csv('digitization_bind.csv')

In [4]:
df_cutting.head(2)

,rank,mname,director,provider,date,country,n_scrn,guest,genre,rating,...,director_score,director_grade,actor_score,actor_grade,grene_score,grene_grade,provider1_power,providera_grade,provider2_power,providerb_grade
0,1,명량,김한민,씨제이이앤엠(주),2014-07-30,한국,1587,17613682,사극,15세이상관람가,...,19.946685,a,12.387048,a,3.336487,d,16.58469,a,16.58469,a
1,2,신과함께-죄와 벌,김용화,롯데쇼핑㈜롯데엔터테인먼트,2017-12-20,한국,1912,14410931,판타지,12세이상관람가,...,16.502886,b,9.926734,c,1.604410,NaN,11.42832,a,11.42832,a

In [5]:
df_cutting_hi = pd.DataFrame([df_cutting.director_grade, df_cutting.actor_grade,df_cutting.grene_grade,df_cutting.providera_grade])

In [6]:
df_cuttingt = df_cutting_hi.T

In [7]:
hi =pd.get_dummies(df_cuttingt, prefix=['director_grade', 'actor_grade', 'grene_grade','providera_grade'])

In [8]:
hi = hi.drop(['director_grade_ ','providera_grade_0','providera_grade_Na'],axis=1)

In [9]:
hi.head()

,director_grade_a,director_grade_b,director_grade_c,director_grade_d,director_grade_e,actor_grade_a,actor_grade_b,actor_grade_c,actor_grade_d,grene_grade_a,...,grene_grade_c,grene_grade_d,grene_grade_e,grene_grade_f,grene_grade_g,providera_grade_a,providera_grade_b,providera_grade_c,providera_grade_d,providera_grade_e
0,1,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
1,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,0,1,0,0,1,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
3,1,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
4,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [227]:
hi.indexs = range(len(hi))

C:\Users\Jin1ib\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.

In [10]:
hi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1730 entries, 0 to 1729
Data columns (total 21 columns):
director_grade_a     1730 non-null uint8
director_grade_b     1730 non-null uint8
director_grade_c     1730 non-null uint8
director_grade_d     1730 non-null uint8
director_grade_e     1730 non-null uint8
actor_grade_a        1730 non-null uint8
actor_grade_b        1730 non-null uint8
actor_grade_c        1730 non-null uint8
actor_grade_d        1730 non-null uint8
grene_grade_a        1730 non-null uint8
grene_grade_b        1730 non-null uint8
grene_grade_c        1730 non-null uint8
grene_grade_d        1730 non-null uint8
grene_grade_e        1730 non-null uint8
grene_grade_f        1730 non-null uint8
grene_grade_g        1730 non-null uint8
providera_grade_a    1730 non-null uint8
providera_grade_b    1730 non-null uint8
providera_grade_c    1730 non-null uint8
providera_grade_d    1730 non-null uint8
providera_grade_e    1730 non-null uint8
dtypes: uint8(21)
memory usage: 35.6 KB

## 이제 우리가 랜덤포레스트를 돌려볼겁니다.
#### 우선 test set을 돌려보도록 하죠

In [21]:
from sklearn.model_selection import train_test_split

In [11]:
df_cutting.head(0)

Empty DataFrame
Columns: [rank, mname, director, provider, date, country, n_scrn, guest, genre, rating, grade, actor, director_score, director_grade, actor_score, actor_grade, grene_score, grene_grade, provider1_power, providera_grade, provider2_power, providerb_grade]
Index: []

[0 rows x 22 columns]

In [16]:
abx = pd.concat([pd.DataFrame(df_cutting.guest),pd.DataFrame(df_cutting.n_scrn),pd.DataFrame(df_cutting.grade),hi],axis=1)

In [17]:
abx.head()

,guest,n_scrn,grade,director_grade_a,director_grade_b,director_grade_c,director_grade_d,director_grade_e,actor_grade_a,actor_grade_b,...,grene_grade_c,grene_grade_d,grene_grade_e,grene_grade_f,grene_grade_g,providera_grade_a,providera_grade_b,providera_grade_c,providera_grade_d,providera_grade_e
0,17613682,1587,8.47,1,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,0,0
1,14410931,1912,7.85,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,14245998,966,9.01,0,0,1,0,0,1,0,...,1,0,0,0,0,1,0,0,0,0
3,13395400,1064,9.01,1,0,0,0,0,1,0,...,0,0,1,0,0,1,0,0,0,0
4,12983330,1072,7.60,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0

In [18]:
X = abx[['n_scrn','grade','director_grade_a','director_grade_b','director_grade_c','director_grade_d','director_grade_e','actor_grade_a','actor_grade_b','actor_grade_c','actor_grade_d','grene_grade_a','grene_grade_b','grene_grade_c','grene_grade_d','grene_grade_e','grene_grade_f','grene_grade_g','providera_grade_a','providera_grade_b','providera_grade_c','providera_grade_d','providera_grade_e']]
y = abx['guest']

In [19]:
abx.head()

,guest,n_scrn,grade,director_grade_a,director_grade_b,director_grade_c,director_grade_d,director_grade_e,actor_grade_a,actor_grade_b,...,grene_grade_c,grene_grade_d,grene_grade_e,grene_grade_f,grene_grade_g,providera_grade_a,providera_grade_b,providera_grade_c,providera_grade_d,providera_grade_e
0,17613682,1587,8.47,1,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,0,0
1,14410931,1912,7.85,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,14245998,966,9.01,0,0,1,0,0,1,0,...,1,0,0,0,0,1,0,0,0,0
3,13395400,1064,9.01,1,0,0,0,0,1,0,...,0,0,1,0,0,1,0,0,0,0
4,12983330,1072,7.60,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0

In [20]:
X_train = train

NameError: name 'train' is not defined

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [155]:
dtree = DecisionTreeClassifier()

In [156]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [70]:
############# Predictions and Evaluation of Decision Tree

In [24]:
predictions = dtree.predict(X_test) # X_test에 대한 예상치를 predictions에 저장한다.

NameError: name 'dtree' is not defined

In [158]:
from sklearn.metrics import classification_report,confusion_matrix

In [171]:
print(classification_report(y_test,predictions)) # 분류보고서를 y_test와 예상치를 비교
# 0.74 = > 74%의 정확도를 의미한다.

             precision    recall  f1-score   support

       8873       0.00      0.00      0.00         0
       9121       0.00      0.00      0.00         1
       9162       0.00      0.00      0.00         1
       9233       0.00      0.00      0.00         0
       9265       0.00      0.00      0.00         0
       9341       0.00      0.00      0.00         1
       9469       0.00      0.00      0.00         1
       9483       0.00      0.00      0.00         1
       9533       0.00      0.00      0.00         1
       9579       0.00      0.00      0.00         0
       9593       0.00      0.00      0.00         1
       9620       0.00      0.00      0.00         1
       9710       0.00      0.00      0.00         0
       9717       0.00      0.00      0.00         0
       9732       0.00      0.00      0.00         1
       9851       0.00      0.00      0.00         0
      10031       0.00      0.00      0.00         1
      10141       0.00      0.00      0.00         1
      10261       0.00      0.00      0.00         1
      10366       0.00      0.00      0.00         0
      10408       0.00      0.00      0.00         1
      10436       0.00      0.00      0.00         1
      10488       0.00      0.00      0.00         1
      10646       0.00      0.00      0.00         1
      10659       0.00      0.00      0.00         1
      10744       0.00      0.00      0.00         0
      10922       0.00      0.00      0.00         1
      11014       0.00      0.00      0.00         1
      11015       0.00      0.00      0.00         1
      11143       0.00      0.00      0.00         1
      11156       0.00      0.00      0.00         1
      11287       0.00      0.00      0.00         1
      11316       0.00      0.00      0.00         1
      11402       0.00      0.00      0.00         1
      11403       0.00      0.00      0.00         1
      11568       0.00      0.00      0.00         1
      11666       0.00      0.00      0.00         1
      11774       0.00      0.00      0.00         0
      12048       0.00      0.00      0.00         1
      12056       0.00      0.00      0.00         1
      12135       0.00      0.00      0.00         1
      12377       0.00      0.00      0.00         1
      12545       0.00      0.00      0.00         1
      12804       0.00      0.00      0.00         1
      12842       0.00      0.00      0.00         1
      12943       0.00      0.00      0.00         1
      13051       0.00      0.00      0.00         0
      13130       0.00      0.00      0.00         0
      13307       0.00      0.00      0.00         1
      13371       0.00      0.00      0.00         1
      13424       0.00      0.00      0.00         1
      13677       0.00      0.00      0.00         1
      13791       0.00      0.00      0.00         1
      14063       0.00      0.00      0.00         1
      14153       0.00      0.00      0.00         1
      14241       0.00      0.00      0.00         1
      14289       0.00      0.00      0.00         1
      14386       0.00      0.00      0.00         0
      14426       0.00      0.00      0.00         1
      14436       0.00      0.00      0.00         1
      14744       0.00      0.00      0.00         1
      14857       0.00      0.00      0.00         1
      14925       0.00      0.00      0.00         1
      14976       0.00      0.00      0.00         1
      14983       0.00      0.00      0.00         1
      15050       0.00      0.00      0.00         0
      15074       0.00      0.00      0.00         1
      15846       0.00      0.00      0.00         1
      15986       0.00      0.00      0.00         1
      16204       0.00      0.00      0.00         1
      16385       0.00      0.00      0.00         1
      16466       0.00      0.00      0.00         1
      16655       0.00      0.00      0.00         0
      16936       0.00      0.00      0.00         1
      17296       0.00      0.00      0.00         1
      17529       0.00      0.00      0.00         1
      17535       0.00      0.00      0.00         1
      17625       0.00      0.00      0.00         1
      17797       0.00      0.00      0.00         1
      17924       0.00      0.00      0.00         1
      18020       0.00      0.00      0.00         1
      18028       0.00      0.00      0.00         1
      18042       0.00      0.00      0.00         1
      18485       0.00      0.00      0.00         1
      19142       0.00      0.00      0.00         1
      19252       0.00      0.00      0.00         1
      19287       0.00      0.00      0.00         1
      19405       0.00      0.00      0.00         1
      19716       0.00      0.00      0.00         0
      19897       0.00      0.00      0.00         1
      20437       0.00      0.00      0.00         1
      20448       0.00      0.00      0.00         1
      20811       0.00      0.00      0.00         1
      21071       0.00      0.00      0.00         0
      21280       0.00      0.00      0.00         1
      21599       0.00      0.00      0.00         1
      21659       0.00      0.00      0.00         1
      22006       0.00      0.00      0.00         1
      22110       0.00      0.00      0.00         1
      22453       0.00      0.00      0.00         1
      22526       0.00      0.00      0.00         1
      22735       0.00      0.00      0.00         1
      22771       0.00      0.00      0.00         1
      22870       0.00      0.00      0.00         1
      23061       0.00      0.00      0.00         1
      23555       0.00      0.00      0.00         1
      23597       0.00      0.00      0.00         1
      23641       0.00      0.00      0.00         1
      23721       0.00      0.00      0.00         0
      24083       0.00      0.00      0.00         1
      24381       0.00      0.00      0.00         1
      24600       0.00      0.00      0.00         1
      25431       0.00      0.00      0.00         1
      25556       0.00      0.00      0.00         1
      25872       0.00      0.00      0.00         1
      26027       0.00      0.00      0.00         1
      26185       0.00      0.00      0.00         1
      26262       0.00      0.00      0.00         1
      26381       0.00      0.00      0.00         1
      26577       0.00      0.00      0.00         1
      26640       0.00      0.00      0.00         1
      26738       0.00      0.00      0.00         1
      26739       0.00      0.00      0.00         1
      26812       0.00      0.00      0.00         1
      27070       0.00      0.00      0.00         1
      27203       0.00      0.00      0.00         1
      27257       0.00      0.00      0.00         1
      27412       0.00      0.00      0.00         1
      27847       0.00      0.00      0.00         1
      28324       0.00      0.00      0.00         1
      28477       0.00      0.00      0.00         1
      28567       0.00      0.00      0.00         1
      29354       0.00      0.00      0.00         1
      29891       0.00      0.00      0.00         1
      30117       0.00      0.00      0.00         1
      30793       0.00      0.00      0.00         1
      31564       0.00      0.00      0.00         1
      31640       0.00      0.00      0.00         0
      31805       0.00      0.00      0.00         1
      32187       0.00      0.00      0.00         1
      32307       0.00      0.00      0.00         1
      33469       0.00      0.00      0.00         1
      33901       0.00      0.00      0.00         0
      33993       0.00      0.00      0.00         1
      34295       0.00      0.00      0.00         1
      34501       0.00      0.00      0.00         1
      34584       0.00      0.00      0.00         1
      34616       0.00      0.00      0.00         1
      34724       0.00      0.00      0.00         1
      35122       0.00      0.00      0.00         1
      35318       0.00      0.00      0.00         1
      35436       0.00      0.00      0.00         1
      35919       0.00      0.00      0.00         1
      35984       0.00      0.00      0.00         1
      36792       0.00      0.00      0.00         1
      38149       0.00      0.00      0.00         1
      38155       0.00      0.00      0.00         1
      38432       0.00      0.00      0.00         1
      38558       0.00      0.00      0.00         1
      39349       0.00      0.00      0.00         1
      39731       0.00      0.00      0.00         1
      40366       0.00      0.00      0.00         1
      40374       0.00      0.00      0.00         1
      40882       0.00      0.00      0.00         1
      41023       0.00      0.00      0.00         1
      41041       0.00      0.00      0.00         1
      41242       0.00      0.00      0.00         0
      42088       0.00      0.00      0.00         1
      42708       0.00      0.00      0.00         1
      43562       0.00      0.00      0.00         1
      43613       0.00      0.00      0.00         1
      43674       0.00      0.00      0.00         1
      43978       0.00      0.00      0.00         1
      44546       0.00      0.00      0.00         1
      44649       0.00      0.00      0.00         1
      44689       0.00      0.00      0.00         1
      44750       0.00      0.00      0.00         0
      44839       0.00      0.00      0.00         1
      45454       0.00      0.00      0.00         0
      45484       0.00      0.00      0.00         1
      45638       0.00      0.00      0.00         1
      45701       0.00      0.00      0.00         1
      46010       0.00      0.00      0.00         1
      46468       0.00      0.00      0.00         1
      46589       0.00      0.00      0.00         1
      46775       0.00      0.00      0.00         1
      47226       0.00      0.00      0.00         1
      47540       0.00      0.00      0.00         1
      47668       0.00      0.00      0.00         1
      48223       0.00      0.00      0.00         1
      48844       0.00      0.00      0.00         1
      48985       0.00      0.00      0.00         1
      49374       0.00      0.00      0.00         1
      50196       0.00      0.00      0.00         1
      50274       0.00      0.00      0.00         1
      50905       0.00      0.00      0.00         1
      51151       0.00      0.00      0.00         1
      51553       0.00      0.00      0.00         1
      51867       0.00      0.00      0.00         1
      52010       0.00      0.00      0.00         1
      52426       0.00      0.00      0.00         1
      52743       0.00      0.00      0.00         1
      53555       0.00      0.00      0.00         1
      53779       0.00      0.00      0.00         1
      54239       0.00      0.00      0.00         1
      54972       0.00      0.00      0.00         1
      55561       0.00      0.00      0.00         0
      55619       0.00      0.00      0.00         1
      55784       0.00      0.00      0.00         1
      56515       0.00      0.00      0.00         1
      56995       0.00      0.00      0.00         1
      58345       0.00      0.00      0.00         1
      58704       0.00      0.00      0.00         1
      59881       0.00      0.00      0.00         1
      59923       0.00      0.00      0.00         1
      60365       0.00      0.00      0.00         1
      60788       0.00      0.00      0.00         1
      60944       0.00      0.00      0.00         1
      61423       0.00      0.00      0.00         1
      62016       0.00      0.00      0.00         1
      62071       0.00      0.00      0.00         1
      65282       0.00      0.00      0.00         1
      65460       0.00      0.00      0.00         1
      65493       0.00      0.00      0.00         1
      66074       0.00      0.00      0.00         1
      66075       0.00      0.00      0.00         1
      66319       0.00      0.00      0.00         1
      66883       0.00      0.00      0.00         0
      69586       0.00      0.00      0.00         1
      70350       0.00      0.00      0.00         1
      71362       0.00      0.00      0.00         1
      71796       0.00      0.00      0.00         1
      73729       0.00      0.00      0.00         1
      75297       0.00      0.00      0.00         1
      77341       0.00      0.00      0.00         1
      78253       0.00      0.00      0.00         1
      79017       0.00      0.00      0.00         1
      79179       0.00      0.00      0.00         1
      80197       0.00      0.00      0.00         1
      80977       0.00      0.00      0.00         1
      82148       0.00      0.00      0.00         1
      82995       0.00      0.00      0.00         1
      83258       0.00      0.00      0.00         1
      83334       0.00      0.00      0.00         1
      85184       0.00      0.00      0.00         1
      85200       0.00      0.00      0.00         1
      86406       0.00      0.00      0.00         1
      87301       0.00      0.00      0.00         1
      88522       0.00      0.00      0.00         1
      89358       0.00      0.00      0.00         1
      90718       0.00      0.00      0.00         1
      92358       0.00      0.00      0.00         1
      93239       0.00      0.00      0.00         1
      94182       0.00      0.00      0.00         1
      94750       0.00      0.00      0.00         1
      95542       0.00      0.00      0.00         1
      96077       0.00      0.00      0.00         1
      97017       0.00      0.00      0.00         1
      97079       0.00      0.00      0.00         1
      97555       0.00      0.00      0.00         1
      97777       0.00      0.00      0.00         1
      98231       0.00      0.00      0.00         1
      98575       0.00      0.00      0.00         1
     100543       0.00      0.00      0.00         1
     101173       0.00      0.00      0.00         1
     101460       0.00      0.00      0.00         1
     103054       0.00      0.00      0.00         1
     103852       0.00      0.00      0.00         1
     106241       0.00      0.00      0.00         1
     107104       0.00      0.00      0.00         1
     107567       0.00      0.00      0.00         1
     108344       0.00      0.00      0.00         1
     117465       0.00      0.00      0.00         1
     118836       0.00      0.00      0.00         1
     122172       0.00      0.00      0.00         1
     122382       0.00      0.00      0.00         1
     122797       0.00      0.00      0.00         1
     123582       0.00      0.00      0.00         1
     124021       0.00      0.00      0.00         1
     124601       0.00      0.00      0.00         1
     125402       0.00      0.00      0.00         1
     125800       0.00      0.00      0.00         1
     131437       0.00      0.00      0.00         1
     131748       0.00      0.00      0.00         1
     131896       0.00      0.00      0.00         1
     132059       0.00      0.00      0.00         1
     134025       0.00      0.00      0.00         1
     135478       0.00      0.00      0.00         1
     137052       0.00      0.00      0.00         1
     137126       0.00      0.00      0.00         1
     137841       0.00      0.00      0.00         1
     141592       0.00      0.00      0.00         1
     143738       0.00      0.00      0.00         1
     146548       0.00      0.00      0.00         1
     150221       0.00      0.00      0.00         0
     151476       0.00      0.00      0.00         1
     151713       0.00      0.00      0.00         1
     151833       0.00      0.00      0.00         1
     152061       0.00      0.00      0.00         1
     155374       0.00      0.00      0.00         1
     156606       0.00      0.00      0.00         1
     161245       0.00      0.00      0.00         1
     166252       0.00      0.00      0.00         1
     169054       0.00      0.00      0.00         1
     169138       0.00      0.00      0.00         1
     169257       0.00      0.00      0.00         1
     169855       0.00      0.00      0.00         1
     170647       0.00      0.00      0.00         1
     172445       0.00      0.00      0.00         1
     173678       0.00      0.00      0.00         1
     174223       0.00      0.00      0.00         1
     175519       0.00      0.00      0.00         1
     175889       0.00      0.00      0.00         1
     177601       0.00      0.00      0.00         1
     182550       0.00      0.00      0.00         0
     183650       0.00      0.00      0.00         1
     185420       0.00      0.00      0.00         1
     186184       0.00      0.00      0.00         1
     186460       0.00      0.00      0.00         1
     189620       0.00      0.00      0.00         1
     190384       0.00      0.00      0.00         1
     192726       0.00      0.00      0.00         1
     193578       0.00      0.00      0.00         1
     197408       0.00      0.00      0.00         1
     198013       0.00      0.00      0.00         1
     200038       0.00      0.00      0.00         1
     201365       0.00      0.00      0.00         1
     203221       0.00      0.00      0.00         0
     205579       0.00      0.00      0.00         1
     210278       0.00      0.00      0.00         0
     212154       0.00      0.00      0.00         1
     216861       0.00      0.00      0.00         1
     217077       0.00      0.00      0.00         1
     217785       0.00      0.00      0.00         1
     217816       0.00      0.00      0.00         1
     221327       0.00      0.00      0.00         1
     223740       0.00      0.00      0.00         1
     224891       0.00      0.00      0.00         0
     228090       0.00      0.00      0.00         1
     228539       0.00      0.00      0.00         1
     229005       0.00      0.00      0.00         1
     233211       0.00      0.00      0.00         1
     236129       0.00      0.00      0.00         1
     238257       0.00      0.00      0.00         1
     257716       0.00      0.00      0.00         1
     258478       0.00      0.00      0.00         1
     259957       0.00      0.00      0.00         1
     262289       0.00      0.00      0.00         1
     267843       0.00      0.00      0.00         1
     272877       0.00      0.00      0.00         1
     289534       0.00      0.00      0.00         1
     289645       0.00      0.00      0.00         1
     292217       0.00      0.00      0.00         1
     298983       0.00      0.00      0.00         1
     305100       0.00      0.00      0.00         1
     306119       0.00      0.00      0.00         1
     313953       0.00      0.00      0.00         1
     315321       0.00      0.00      0.00         1
     315348       0.00      0.00      0.00         1
     316788       0.00      0.00      0.00         1
     317505       0.00      0.00      0.00         0
     320923       0.00      0.00      0.00         1
     321550       0.00      0.00      0.00         1
     324420       0.00      0.00      0.00         1
     329029       0.00      0.00      0.00         1
     333935       0.00      0.00      0.00         1
     344766       0.00      0.00      0.00         1
     350563       0.00      0.00      0.00         1
     364415       0.00      0.00      0.00         1
     373344       0.00      0.00      0.00         1
     378729       0.00      0.00      0.00         1
     380581       0.00      0.00      0.00         1
     384789       0.00      0.00      0.00         1
     385934       0.00      0.00      0.00         0
     387409       0.00      0.00      0.00         1
     387795       0.00      0.00      0.00         1

C:\Users\Jin1ib\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Jin1ib\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

In [76]:
print("오차 행렬:\n{}".format(confusion_matrix(y_test,predictions)))

오차 행렬:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [25]:
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

In [26]:
rfc = RandomForestRegressor(n_estimators=100,
                              n_jobs=-1,
                              random_state=0,
                           max_depth=2)

In [27]:
rfc.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=2,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [29]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1211 entries, 1279 to 863
Data columns (total 23 columns):
n_scrn               1211 non-null int64
grade                1211 non-null float64
director_grade_a     1211 non-null uint8
director_grade_b     1211 non-null uint8
director_grade_c     1211 non-null uint8
director_grade_d     1211 non-null uint8
director_grade_e     1211 non-null uint8
actor_grade_a        1211 non-null uint8
actor_grade_b        1211 non-null uint8
actor_grade_c        1211 non-null uint8
actor_grade_d        1211 non-null uint8
grene_grade_a        1211 non-null uint8
grene_grade_b        1211 non-null uint8
grene_grade_c        1211 non-null uint8
grene_grade_d        1211 non-null uint8
grene_grade_e        1211 non-null uint8
grene_grade_f        1211 non-null uint8
grene_grade_g        1211 non-null uint8
providera_grade_a    1211 non-null uint8
providera_grade_b    1211 non-null uint8
providera_grade_c    1211 non-null uint8
providera_grade_d    1211 non-null uint8
providera_grade_e    1211 non-null uint8
dtypes: float64(1), int64(1), uint8(21)
memory usage: 53.2 KB

In [40]:
print(rfc.predict([[1605, # 스크린수
                    9.33, # 평점
                    0, 0, 1, 0, 0, # 감독파워
                    0, 1, 0, 0,    # 배우파워
                    0, 1, 0, 0, 0, 0, 0, # 장르파워
                    1, 0, 0, 0, 0  # 배급사파워
                   ]]))

[4765513.48404301]

In [28]:
preds = rfc.predict(X_test)
print('MAE:', metrics.mean_absolute_error(y_test, preds))
print('MSE:', metrics.mean_squared_error(y_test, preds))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, preds)))

MAE: 548103.7690294113
MSE: 1702746758295.5076
RMSE: 1304893.3896282513

In [172]:
print('accuracy:', metrics.accuracy_score(y_test,preds))

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [130]:
from sklearn.metrics import classification_report,confusion_matrix

In [131]:
print(classification_report(y_test,predictions))

ValueError: Mix type of y not allowed, got types {'continuous', 'multiclass'}

In [85]:
print(confusion_matrix(y_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]